version: "3.9"
services:
  app:
    build:
      args:
        user: platine
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: platine-php
    container_name: platine-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
      - platine
      
  webserver:
    image: nginx:alpine
    container_name: platine-web
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - platine

networks:
  platine:
    driver: bridge
